pmedia/urls.py
from django.contrib import admin
from django.urls import path
from andhrapradesh.views import *
from accounts.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('andhrapradesh/', home),
    path('andhrapradesh/<int:districts_id>/',details, name = 'details'),
    path('andhrapradesh/complaint/<int:complaint_id>/',complaint, name = 'complaint'),
    path('andhrapradesh/post_complaint/',post_complaint_view, name = 'post_complaint'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name = 'logout.html'), name = 'logout'),
    path('accounts/register/', register_view),
    #path('accounts/logout/', logout_view)

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

andhrapradesh/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class district(models.Model):
    district_ident = models.CharField(max_length = 10)
    district_name = models.CharField(max_length = 50)
    district_logo = models.CharField(max_length = 1000)
    district_pincode = models.CharField(max_length = 6)

    def __str__(self):
        return self.district_name

class assemblies(models.Model):
    districts = models.ForeignKey(district, on_delete=models.CASCADE)
    assembly = models.CharField(max_length = 20)
    assembly_logo = models.CharField(max_length = 1000)

    def __str__(self):
        return self.assembly


class public_complaints(models.Model):
    complaint = models.ForeignKey(assemblies, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete= models.CASCADE,related_name='post_complain', null = True)
    created_on = models.DateTimeField(auto_now_add=True, null = True)
    complaint_type = models.CharField(max_length = 20)
    complaint_name = models.CharField(max_length = 100)
    description = models.TextField(max_length = 10000)
    complaint_photo = models.ImageField(upload_to = 'images/')

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.complaint_name

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model


User = get_user_model()

class UserLogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username = username, password = password)

            if not user:
                raise forms.ValidationError('This user does not exist.')

            if not user.check_password(password):
                raise forms.ValidationError("Entered password is invalid.")

            if not user.is_active:
                raise forms.ValidationError("This user is not in active")

        return super(UserLogInForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label = 'Enter email')
    email2 = forms.EmailField(label = 'confirm email')
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')

        if email != email2:
            raise forms.ValidationError('email must be same.')

        email_eq = User.objects.filter(email = email)

        if email_eq.exists():
            raise forms.ValidationError('This email already exist.')

        return super(UserRegisterForm, self).clean(*args, **kwargs)

andhrapradesh/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *

class public_complaints_form(forms.ModelForm):

    class Meta():
        model = public_complaints
        fields = '__all__'
        #fields = ['complaint', 'complaint_type', 'complaint_name', 'description', 'complaint_photo']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, get_user_model, login, logout
from .forms import UserRegisterForm, UserLogInForm
from django.contrib.auth.decorators import login_required

# Create your views here.
########################### login and signin module ################################################
def login_view(request):
    next = request.GET.get('next')
    form = UserLogInForm(request.POST, None)

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(username = username, password = password)

        login(request, user)
        if next:
            return redirect(next)
        return redirect('/andhrapradesh/')

    context = {
            'form' : form,
    }

    return render(request, 'login.html', context)


def register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST, None)

    if form.is_valid():
        user = form.save(commit = False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username = user.username, password = password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('/andhrapradesh/')

    context = {
            'form' : form,
    }

    return render(request, 'signin.html', context)

'''
def logout_view(request):
    """
    Removes the authenticated user's ID from the request and flushes their
    session data.
    """
    # Dispatch the signal before the user is logged out so the receivers have a
    # chance to find out *who* logged out.
    user = getattr(request, 'user', None)
    if hasattr(user, 'is_authenticated') and not user.is_authenticated():
        user = None
    user_logged_out.send(sender=user.__class__, request=request, user=user)

    request.session.flush()
    if hasattr(request, 'user'):
        from django.contrib.auth.models import AnonymousUser
        request.user = AnonymousUser()
    return redirect('/')
'''

def logout_view(request):
#    for sesskey in request.session.keys():
#        del request.session[sesskey]
    auth.logout(request)
    return redirect('/')

########################### end of login and signin module ################################################

andhrapradesh/views.py
from django.shortcuts import render, redirect
from django.http import *
from django.template import loader
from .models import district, assemblies, public_complaints
from .forms import *
# Create your views here.
#login and signin module
from django.contrib.auth import authenticate, get_user_model, login, logout

###############################################

from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    all_dist = district.objects.all()
    context = {
        'all_dist': all_dist
    }
    return render(request, 'home.html', context)


def index(request):
    all_dist = district.objects.all()
    context = {
        'all_dist': all_dist
    }
    return render(request, 'index.html', context)


def details(request, districts_id):
    detail = district.objects.get(pk = districts_id)
    return render(request, 'details.html', {'detail': detail})

def complaint(request, complaint_id):
    detail_comp = assemblies.objects.get(pk = complaint_id)
    template = loader.get_template('complaint.html')
    context = {
        "detail_comp": detail_comp
    }
    return HttpResponse(template.render(context, request))


def post_complaint_view(request):
    if request.method == "POST":
        form = public_complaints_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/andhrapradesh/post_complaint/')
    else:
        form = public_complaints_form()
    return render(request, 'post_complaint.html', {'form': form})

pmedia/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    return render(request, 'home.html')

accounts/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>

    <center>
    <h1><u> Login form </h1>
    <form method="POST">

      {% csrf_token %}

      {{ form.as_p }}
      <input type="submit" />
    </form>
    </center>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/logout.html
<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <style>
    ul {
      list-style-type: none;
      margin: 0;
      padding: 0;
      width: 200px;
      background-color: #f1f1f1;
    }

    li a {
      display: block;
      color: #000;
      padding: 8px 16px;
      text-decoration: none;
    }

    /* Change the link color on hover */
    li a:hover {
      background-color: #555;
      color: white;
    }

    .nav {
      float: right;
      align-items: right;
    }

    </style>
  </head>
  <body>
    <h1 style="background-color: #f1f1f1; height: 60px" >&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp<a href="/">E-Complaint</a></h1>

    <ul class="nav navbar-nav navbar-right">
            <li class="">
                                    <a href="/accounts/register/">
                                        <span class="glyphicon glyphicon-user" aris-hidden = "true"></span>&nbsp;Signin
                                    </a>
                            </li>
                            <li class="">
                                <a href="/accounts/login/">
                                    <span class="glyphicon glyphicon-log-in" aris-hidden = "true"></span>&nbsp;Login
                                </a>
                            </li>
    </ul>

    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="#news">News</a></li>
      <li><a href="#contact">Contact</a></li>
      <li><a href="#about">About</a></li>
    </ul>
<center>
    <h3> your logged_out successfully </h3>
</center>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/signin.html
<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <center>
      <h1><u> Register Form </h1>
    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" />
    </form>
  </center>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

andhrapradesh/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title> {% block title %} PublicMedia {% endblock %} </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
{% block style %}

{% endblock %}

</head>

<body>

<h1 style="background-color: #f1f1f1; height: 50px" > &nbsp
<img src="{% static 'images/logo.jpg' %}" alt="My image" height="50px" width=50px/>
  <a href="/">E-Complaint</a>
</h1>

<ul class="nav navbar-nav navbar-right">
  {% if user.is_authenticated %}
                      <li class="">
                            <a href="{% url 'logout' %}">
                              <span class="glyphicon glyphicon-log-out" aris-hidden = "true"></span>&nbsp;Logout
                            </a>
                        </li>
  {% else %}
                        <li class="">
                                <a href="/accounts/register/">
                                    <span class="glyphicon glyphicon-user" aris-hidden = "true"></span>&nbsp;Signin
                                </a>
                        </li>
                        <li class="">
                            <a href="/accounts/login/">
                                <span class="glyphicon glyphicon-log-in" aris-hidden = "true"></span>&nbsp;Login
                            </a>
                        </li>
{% endif %}


                </ul>


<ul>
  <li><a href="/">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
</ul>


{% block body %}

{% endblock %}

{% if user.is_authenticated %}

    <a href="/andhrapradesh/post_complaint/">
        <center> <button type="submit" class="btn btn-info" >Post_Complaint</button> </center><br><br>
    </a>

{% else %}
    <a href="/andhrapradesh/login">

{% endif %}



 {% block footer %}


 <footer class="container-fluid bg-4 text-center" style = "padding-top: 70px; padding-bottom: 70px;">
  <p>E-Complaint Made By <a href="https://www.e-complaint.com">www.e-complaint.com</a></p>
</footer>
 {% endblock %}


 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>

andhrapradesh/templates/complaint.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<center> <h1><b><u> {{detail_comp.assembly}}</h1> </center>

<hr>
{% if detail_comp %}
<div class="row container-fluid" style="margin-top: 10px;">
    {% for ass in detail_comp.public_complaints_set.all %}
    <div class="col-sm-6 col-md-6">
        {{ass.created_on}} | <font color="green">  {{ass.created_by}} </font> <br> </br>
         <img src = "{{ ass.complaint_photo.url }}" alt="image" class="thumbnail" style="width:600px;height:380px; border-radius: 8px;">

        <b><h4>{{ass.complaint_name}}  </h4>

          <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a> &nbsp
          <a href="/delete/{{ employee.id }}">Delete</a>
        </b>

        <p>{{ass.description}}</p>
        <br>
    </div>
    {% endfor %}
</div>

{% else %}
    <h3> You don't have any Assemblies </h3>
{% endif %}

{% endblock %}

andhrapradesh/templates/details.html
{% extends 'base.html' %}

{% block body %}
<center> <h1><u><b>List of Assemblies in {{detail.district_name}}</h1> </center>

<hr>
{% if detail %}
<div class="row container-fluid" style="margin-top: 10px">
    {% for ass in detail.assemblies_set.all %}
        <div class="col-sm-4 col-md-3">
          <center> <img src = {{ass.assembly_logo}} alt="image" class="thumbnail" style="width:310px;height:250px; border-radius: 6px;">
          <b><u><a href = "/andhrapradesh/complaint/{{ass.id}}"> {{ ass.assembly }} </a></u></b> </center> <br>
        </div>
    {% endfor %}
</div>

{% else %}
    <h3> You don't have any Assemblies </h3>
{% endif %}
<!--
<ul>
    {% for ass in detail.assemblies_set.all %}
    <li> {{ ass.assembly }} </li>
    {% endfor %}
</ul>
-->
{% endblock %}

andhrapradesh/templates/home.html
{% extends "base.html" %}

{% block body %}

    <center><u><h2><b>Districts in AP </b></h2></center>
    <hr>
    {% if all_dist %}
    <div class="row container-fluid" style="margin-top: 10px">
        {% for dist in all_dist %}
            <div class="col-sm-4 col-md-3">
              <center> <img src = {{dist.district_logo}} alt="image" class="thumbnail" style="width:310px;height:250px;">
              <b><u><a href = "/andhrapradesh/{{ dist.id }}"> {{ dist.district_name }} </a></u></b> </center> <br>
            </div>
        {% endfor %}
    </div>

    {% else %}
        <h3> You don't have any districts </h3>
    {% endif %}

{% endblock %}

andhrapradesh/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

    <center><h1><u><b> Districts in AP </h1></center>
    <hr>
    {% if all_dist %}
    <div class="row container-fluid" style="margin-top: 10px">
        {% for dist in all_dist %}
            <div class="col-sm-4 col-md-3">
              <center> <img src = {{dist.district_logo}} alt="image" class="thumbnail" style="width:310px;height:250px; border-radius: 6px;">
              <b><u><a href = "/andhrapradesh/{{ dist.id }}"> {{ dist.district_name }} </a></u></b> </center> <br>
            </div>
        {% endfor %}
    </div>

    {% else %}
        <h3> You don't have any districts </h3>
    {% endif %}

{% endblock %}

andhrapradesh/templates/post_complaint.html
<!doctype html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>

{% block body %}

{% if user.is_authenticated %}
<br>
<center >
  <h1> <u> Post Complaint </h1> <br>
<div class="container" >
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      {{ form.as_p }}
    </div>
    <button type="submit"> submit </a></button>
</form>
</div>

</center>

{% else %}
<form method="post" action="{% url 'login' %}">
{% csrf_token %}

{% endif %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/boostrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>

andhrapradesh/templates/temp_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title> {% block title %} PublicMedia {% endblock %} </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>

<body>

<h1 style="background-color: #f1f1f1 ">Vertical Navigation Bar</h1>

<ul class="nav navbar-nav navbar-right">
                        <!-- <li class="">
                                <a href="accounts/register">
                                    <span class="glyphicon glyphicon-user" aris-hidden = "true"></span>&nbsp;Signin
                                </a>
                        </li> -->
                        <li class="">
                            <a href="/">
                                <span class="glyphicon glyphicon-log-out" aris-hidden = "true"></span>&nbsp;Logout
                            </a>
                        </li>

                </ul>

<ul>
  <li><a href="/">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
</ul>







{% block body %}


{% endblock %}

{% block footer %}

 <footer class="footer text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Location</h4>
          <p class="lead mb-0">2215 John Daniel Drive
            <br>Clark, MO 65243</p>
        </div>
        <div class="col-md-4 mb-5 mb-lg-0">
          <h4 class="text-uppercase mb-4">Around the Web</h4>
          <!--
          <ul class="list-inline mb-0">
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                <i class="fab fa-fw fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                <i class="fab fa-fw fa-google-plus-g"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                <i class="fab fa-fw fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                <i class="fab fa-fw fa-linkedin-in"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-outline-light btn-social text-center rounded-circle" href="#">
                <i class="fab fa-fw fa-dribbble"></i>
              </a>
            </li>
          </ul>
        -->
        </div>
        <div class="col-md-4">
          <h4 class="text-uppercase mb-4">About Freelancer</h4>
          <p class="lead mb-0">Freelance is a free to use, open source Bootstrap theme created by
            <a href="#">Start Bootstrap</a>.</p>
        </div>
      </div>
    </div>
  </footer>

  <div class="copyright py-4 text-center text-white">
    <div class="container">
      <small>Copyright &copy; Your Website 2018</small>
    </div>
  </div>

 {% endblock %}


 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
</html>